-- ============================================================
-- MiTaller - Sistema Web de Gestión y Trazabilidad para Taller Mecánico
-- 2.ª Entrega - Esquema relacional de base de datos
-- Motor previsto: H2
-- ============================================================
--
-- El esquema representa exclusivamente el MVP definido para MiTaller.
-- Las reglas de transición entre estados y la validación del rol MECANICO
-- para el responsable de una orden se controlarán en la capa Service.
-- ============================================================

-- ------------------------------------------------------------
-- 1. Usuario
-- Representa a las personas que operan el sistema.
-- ------------------------------------------------------------
CREATE TABLE usuario (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_completo VARCHAR(120) NOT NULL,
    email VARCHAR(120) UNIQUE,
    rol VARCHAR(40) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_usuario_rol
        CHECK (rol IN ('RECEPCION_ADMINISTRACION', 'MECANICO'))
);

-- ------------------------------------------------------------
-- 2. Cliente
-- ------------------------------------------------------------
CREATE TABLE cliente (
    id_cliente BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    dni_cuit VARCHAR(20) UNIQUE,
    telefono VARCHAR(30),
    email VARCHAR(120),
    direccion VARCHAR(200),
    fecha_registro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ------------------------------------------------------------
-- 3. Vehiculo
-- Cada vehículo pertenece a un único cliente.
-- ------------------------------------------------------------
CREATE TABLE vehiculo (
    id_vehiculo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patente VARCHAR(15) NOT NULL UNIQUE,
    marca VARCHAR(60) NOT NULL,
    modelo VARCHAR(60) NOT NULL,
    anio INT,
    id_cliente BIGINT NOT NULL,

    CONSTRAINT fk_vehiculo_cliente
        FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente)
        ON DELETE RESTRICT
);

-- ------------------------------------------------------------
-- 4. Orden de Trabajo
-- Entidad central del sistema.
-- id_mecanico puede ser NULL únicamente mientras la orden permanezca
-- en RECIBIDO. Antes de pasar a EN_DIAGNOSTICO debe estar asignado.
-- ------------------------------------------------------------
CREATE TABLE orden_trabajo (
    id_orden BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_vehiculo BIGINT NOT NULL,
    id_mecanico BIGINT,
    fecha_ingreso TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_entrega TIMESTAMP,
    kilometraje_ingreso INT NOT NULL,
    motivo_ingreso VARCHAR(1000) NOT NULL,
    diagnostico VARCHAR(2000),
    observaciones VARCHAR(2000),
    estado VARCHAR(30) NOT NULL DEFAULT 'RECIBIDO',

    CONSTRAINT chk_orden_kilometraje
        CHECK (kilometraje_ingreso >= 0),

    CONSTRAINT chk_orden_estado
        CHECK (estado IN (
            'RECIBIDO',
            'EN_DIAGNOSTICO',
            'EN_REPARACION',
            'ESPERANDO_REPUESTO',
            'CONTROL_FINAL',
            'FINALIZADO',
            'ENTREGADO'
        )),

    CONSTRAINT fk_orden_vehiculo
        FOREIGN KEY (id_vehiculo) REFERENCES vehiculo(id_vehiculo)
        ON DELETE RESTRICT,

    CONSTRAINT fk_orden_mecanico
        FOREIGN KEY (id_mecanico) REFERENCES usuario(id_usuario)
        ON DELETE RESTRICT
);

-- ------------------------------------------------------------
-- 5. Detalle de Trabajo
-- Registra las tareas concretas realizadas dentro de una orden.
-- ------------------------------------------------------------
CREATE TABLE detalle_trabajo (
    id_detalle BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_orden BIGINT NOT NULL,
    descripcion VARCHAR(1500) NOT NULL,
    fecha_registro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_detalle_orden
        FOREIGN KEY (id_orden) REFERENCES orden_trabajo(id_orden)
        ON DELETE RESTRICT
);

-- ------------------------------------------------------------
-- 6. Historial de Estado de la Orden
-- Cada registro representa una transición real de la orden.
-- La creación inicial en RECIBIDO no genera historial; el primer registro
-- será, por ejemplo, RECIBIDO -> EN_DIAGNOSTICO.
-- ------------------------------------------------------------
CREATE TABLE historial_estado_orden (
    id_historial BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_orden BIGINT NOT NULL,
    estado_anterior VARCHAR(30) NOT NULL,
    estado_nuevo VARCHAR(30) NOT NULL,
    fecha_cambio TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id_usuario BIGINT NOT NULL,
    observacion VARCHAR(500),

    CONSTRAINT chk_historial_estado_anterior
        CHECK (estado_anterior IN (
            'RECIBIDO',
            'EN_DIAGNOSTICO',
            'EN_REPARACION',
            'ESPERANDO_REPUESTO',
            'CONTROL_FINAL',
            'FINALIZADO',
            'ENTREGADO'
        )),

    CONSTRAINT chk_historial_estado_nuevo
        CHECK (estado_nuevo IN (
            'RECIBIDO',
            'EN_DIAGNOSTICO',
            'EN_REPARACION',
            'ESPERANDO_REPUESTO',
            'CONTROL_FINAL',
            'FINALIZADO',
            'ENTREGADO'
        )),

    CONSTRAINT chk_historial_cambio_real
        CHECK (estado_anterior <> estado_nuevo),

    CONSTRAINT fk_historial_orden
        FOREIGN KEY (id_orden) REFERENCES orden_trabajo(id_orden)
        ON DELETE RESTRICT,

    CONSTRAINT fk_historial_usuario
        FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario)
        ON DELETE RESTRICT
);

-- ------------------------------------------------------------
-- Índices de apoyo para las consultas principales del sistema.
-- ------------------------------------------------------------
CREATE INDEX idx_vehiculo_cliente
    ON vehiculo(id_cliente);

CREATE INDEX idx_orden_vehiculo
    ON orden_trabajo(id_vehiculo);

CREATE INDEX idx_orden_mecanico
    ON orden_trabajo(id_mecanico);

CREATE INDEX idx_orden_estado
    ON orden_trabajo(estado);

CREATE INDEX idx_detalle_orden
    ON detalle_trabajo(id_orden);

CREATE INDEX idx_historial_orden
    ON historial_estado_orden(id_orden);

CREATE INDEX idx_historial_usuario
    ON historial_estado_orden(id_usuario);
